name: WPS Git Deploy
description: >
  Commits and pushes changes to a git repository. Written as a docker
  container action.
inputs:
  repository:
    description: The ssh url of the target repository.
    required: true
  # ssh_public_key:
  #   description: >
  #     SSH key used to push to the registry. The SSH key is configured
  #     with the local git config, enabling this action ro run
  #     authenticated git commands.
  #   required: false
  ssh_private_key:
    description: >
      SSH key used to push to the registry. The SSH key is configured
      with the local git config, enabling this action ro run
      authenticated git commands.
    required: true
  ssh_known_hosts:
    description: Optional. Known hosts to run ssh commands against.
    required: false
  ssh_password:
    description: Password for SSH command.
    required: true
  remote_branch:
    description: Optional. Set the remote branch. Defaults to same branch the process is running.
    required: false
  debug:
    description: Verbose output.
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: red
  icon: anchor
