name: check action
on: [ push, pull_request ]
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        run: shellcheck entrypoint.sh